import type { Metadata } from "next";
import { Bebas_Neue, Plus_Jakarta_Sans, Inter } from "next/font/google";
import "./globals.scss";
import "leaflet/dist/leaflet.css";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import styles from "./Layout.module.scss";

import Providers from "@/app/providers/Providers";
import { ToastContainer } from "react-toastify";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-logo",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-primary",
});

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "AgnesNora Studio TisUsecase",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${bebasNeue.variable} ${plusJakartaSans.variable} ${inter.variable}`}
      >
        <NextIntlClientProvider>
          <Providers>
            <div className={styles.appContainer}>
              <Navbar />
              <div className={styles.mainContainer}>
                <Header />
                <main>{children}</main>
              </div>
            </div>
            <ToastContainer />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
